<?php
require("./TimeStamp.php");
class ShopStamp extends TimeStamp { // ideal for shops
    public $DeliveryDate; public $PaymentDate;
    // parent functions
    function __construct($timestamp = false, $DeliveryDate, $PaymentDate)
    {
        parent::__construct($timestamp); // simply inheriting timestamp
        $this->DeliveryDate = $DeliveryDate;
        $this->PaymentDate = $PaymentDate;
    }
    public function addDuration($seconds)
    {
        return parent::addDuration($seconds); // TODO: Change the autogenerated stub
    }
    protected function getDuration()
    {
        parent::getDuration(); // TODO: Change the autogenerated stub
    }

    // sets and gets
    public function setDeliveryDate($DeliveryDate)
    {
        $this->DeliveryDate = $DeliveryDate;
    }

    public function setPaymentDate($PaymentDate)
    {
        $this->PaymentDate = $PaymentDate;
    }

    public function getDeliveryDate() {
        return $this->DeliveryDate;
    }

    public function getPaymentDate() {
        return $this->PaymentDate;
    }
    public function addDeliveryDate($time) {
        $this->DeliveryDate += $time;
    }
    public function addPaymentDate($time) {
        $this->PaymentDate += $time;
    }
    function reducePaymentDate($time) {
        if ($this->PaymentDate < $time) return false;
        // making sure that the payment date wont be in negatives
        $this->PaymentDate -= $time;
        return true;
    }
    function reduceDeliveryDate($time) {
        if ($this->PaymentDate < $time) return false;
        $this->DeliveryDate -= $time;
        return true;
    }
    public function getDurationAdd()
    {
        return parent::getDurationAdd(); // TODO: Change the autogenerated stub
    }
    public function getTimestamp()
    {
        return parent::getTimestamp(); // TODO: Change the autogenerated stub
    }
}